### PR TITLE
Updated to include only urban households.

### PR DESCRIPTION
**Pull request by Davanden**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by KaliUSAsdgs** [comment]
I have just processed your pull request for SDG indicator:  11.1.1
At your earliest convenience, please check that the statistics/graph look correct.  If you have any questions, please do not hesitate to contact me.
Thank you for your help in providing these statistics!
Sincerely, Kali

**Comment by Davanden** [comment]
Kali,

Thank you for this notice.  The entries are correct.

Dav Vandenbroucke
Senior Economist
U.S. Department of Housing & Urban Development
451 7th Street SW, Room 8222
Washington, DC 20410

Email david.a.vandenbroucke@hud.gov<mailto:david.a.vandenbroucke@hud.gov>
Phone 202-402-5890

I disclaim all disclaimers

**Comment by Davanden** [comment]
This is good.  "This looks like a scam, but it really isn't."  Trying to leverage the notoriety of these blatant frauds against themselves.

--Dav

-----Original Message-----
From: Kamal Mukhar <kamal.mukhar@gmail.com> 
Sent: Wednesday, May 22, 2019 5:06 AM
Subject: Monetary Transaction

Attn: Sir/Madam
Desperate times often calls for desperate measures. I am fully aware of the risk am taking by sending this mail to you. At the least, it may end in your recycle bin unread or flagged as a scam; or at worst it may be received by people that are ill intention or seeks my family's destruction. I however hope it finds its way to a heart with emphatic intuition.
May I appeal to your business sense; if you are capable and willing, because I have an urgent need to form a profitable business relationship. As a result of my country's current political situation, my family is desirous of moving our funds into any reliably profitable and lucrative sector.we are looking for individuals with financial management know-how or connections that can handle the investment and management of a very large sum.
if you have any idea, interest or you need further clarification please reply me urgently on my private email:  kamal.mukhar@hotmail.com 
Yours Sincerely,
Kamal Mukhar

**Comment by KaliUSAsdgs** [comment]
Good morning, David
Did you get this via Github?

**Pull request merged**
