### PR TITLE
11.1.1 Added values for 2017

### PR DESCRIPTION
**Pull request by Davanden**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by KaliUSAsdgs** [comment]
I have just processed your pull request for SDG indicator:  11.1.1
At your earliest convenience, please check that the statistics/graph look correct.  If you have any questions, please do not hesitate to contact me.
Thank you for your help in providing these statistics!
Sincerely, Kali

**Comment by Davanden** [comment]
Kali,

I need to correct this.  The values I entered were for all households, not all urban households.  The difference is very small.  I knew that I had made this mistake almost immediately after submitting, but I decided to wait until you had processed the entry before trying to fix it.

Dav Vandenbroucke
Senior Economist
U.S. Department of Housing & Urban Development
451 7th Street SW, Room 8222
Washington, DC 20410

Email david.a.vandenbroucke@hud.gov<mailto:david.a.vandenbroucke@hud.gov>
Phone 202-402-5890

I disclaim all disclaimers

**Comment by KaliUSAsdgs** [comment]
Ok

Sincerely,
Kali


On May 16, 2019, at 7:11 AM, Davanden <notifications@github.com<mailto:notifications@github.com>> wrote:

Kali,

I need to correct this. The values I entered were for all households, not all urban households. The difference is very small. I knew that I had made this mistake almost immediately after submitting, but I decided to wait until you had processed the entry before trying to fix it.

Dav Vandenbroucke
Senior Economist
U.S. Department of Housing & Urban Development
451 7th Street SW, Room 8222
Washington, DC 20410

Email david.a.vandenbroucke@hud.gov<mailto:david.a.vandenbroucke@hud.gov><mailto:david.a.vandenbroucke@hud.gov>
Phone 202-402-5890

I disclaim all disclaimers

**Comment by Davanden** [comment]
I think I’ve made the corrections.  I have trouble telling if things are working on that site.  I have not received an email about the changes being submitted.

Dav Vandenbroucke
Senior Economist
U.S. Department of Housing & Urban Development
451 7th Street SW, Room 8222
Washington, DC 20410

Email david.a.vandenbroucke@hud.gov<mailto:david.a.vandenbroucke@hud.gov>
Phone 202-402-5890

I disclaim all disclaimers

**Comment by KaliUSAsdgs** [comment]
I am offsite this afternoon, but will look at it later today .
Thanks, David

Sincerely,
Kali


On May 16, 2019, at 12:04 PM, Davanden <notifications@github.com<mailto:notifications@github.com>> wrote:

I think I’ve made the corrections. I have trouble telling if things are working on that site. I have not received an email about the changes being submitted.

Dav Vandenbroucke
Senior Economist
U.S. Department of Housing & Urban Development
451 7th Street SW, Room 8222
Washington, DC 20410

Email david.a.vandenbroucke@hud.gov<mailto:david.a.vandenbroucke@hud.gov><mailto:david.a.vandenbroucke@hud.gov>
Phone 202-402-5890

I disclaim all disclaimers

**Pull request merged**
