### PR TITLE
Update indicator_9-1-2.csv

### PR DESCRIPTION
**Pull request by sbeningo**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by KaliUSAsdgs** [comment]
I have just processed your pull request for SDG indicator:  9.1.2
At your earliest convenience, please check that the statistics/graph look correct.  If you have any questions, please do not hesitate to contact me.
Thank you for your help in providing these statistics!
Sincerely, Kali

**Comment by KaliUSAsdgs** [comment]
I have just processed your pull request for SDG indicator:  9.1.2
At your earliest convenience, please check that the statistics/graph look correct.  If you have any questions, please do not hesitate to contact me.
Thank you for your help in providing these statistics!
Sincerely, Kali

**Comment by sbeningo** [comment]
Kali,
     I cannot find the graph.  Where is the graph?
Steven Beningo
U.S. Department of Transportation
Bureau of Transportation Statistics
1200 New Jersey Avenue SE, Room E34-301, RTS-34
Washington, DC 20590
(202) 366-9683

**Comment by KaliUSAsdgs** [comment]
Hi Steven,
It should be on the main page but it doesn’t look like the data is updated yet (if you don’t see it by your cob, please check tomorrow and let me know status).
https://gsa.github.io/sdg-indicators-usa/9-1-2/

Thanks for your patience.

**Comment by sbeningo** [comment]
Kali,
     In my opinion, the graph is horrible.  I have no idea why you would just show the air passenger-kilometers data, and not any of the other data.  Worse – the metadata for this graph covers all of the data that we submitted, meaning that most of the metadata for the graph have no relevance to the data being displayed in the graph.  This graph needs to be fixed.

Steven Beningo
U.S. Department of Transportation
Bureau of Transportation Statistics
1200 New Jersey Avenue SE, Room E34-301, RTS-34
Washington, DC 20590
(202) 366-9683

**Comment by sbeningo** [comment]
Kali,
     Please let me know when the new data are available for checking.
           Steve

From: Beningo, Steven (OST)
Sent: Wednesday, May 15, 2019 4:43 PM
To: GSA/sdg-data-usa <reply@reply.github.com>
Subject: RE: [GSA/sdg-data-usa] Update indicator_9-1-2.csv (#30)

Kali,
     In my opinion, the graph is horrible.  I have no idea why you would just show the air passenger-kilometers data, and not any of the other data.  Worse – the metadata for this graph covers all of the data that we submitted, meaning that most of the metadata for the graph have no relevance to the data being displayed in the graph.  This graph needs to be fixed.

Steven Beningo
U.S. Department of Transportation
Bureau of Transportation Statistics
1200 New Jersey Avenue SE, Room E34-301, RTS-34
Washington, DC 20590
(202) 366-9683

**Comment by KaliUSAsdgs** [comment]
Dear Steven,
I definitely know the graph needs work—I’ve suggested a double y-axis plot of passenger vs. freight volume…
HOWEVER, you are the SME, so please let us know what you would like the graph to look like.

**Comment by KaliUSAsdgs** [comment]
I will forward issue to our developers:
I know it is not updated yet.
For this indicator (and 2 or 3 others), I noticed an error message “branch has conflicts that much be resolved…”

Thanks for your patience—there were 70+ submissions I had to look at.

**Comment by sbeningo** [comment]
Kali,
     I would suggest a graph of either all of the freight data that we submitted, or all of the passenger data that we submitted (your choice).  This means that all of the modes of transportation are displayed.  Only the metadata for the freight data or the passenger data should be displayed (depending upon whether you want to show freight or passenger data in the graph).  This would be far more meaningful for the data user (as it would allow the user to compare modes) than a single line showing just one data series covering a single mode.
             Steve

**Comment by KaliUSAsdgs** [comment]
Dear Steven,
Thank you for your helpful comments—I’ll forward to our developers.

Also, while looking at the table, I noticed a weird data point in 2015… which may have caused the error.  Could you please send me the data so I can input it from my end?  Thanks.

[cid:image002.jpg@01D50B3F.EC9F5D90]

**Comment by sbeningo** [comment]
Kali,
      I have attached the source data in a spreadsheet form.  I am not seeing any weird 2015 data in the spreadsheet.
              Steve

**Comment by sbeningo** [comment]
Kali,
     I see that the erroneous data point has been fixed – thank you.  However, the problems of only one mode (Air) being shown at https://sdg.data.gov/9-1-2/, and the mismatch between the metadata (which covers our entire SDG 9.1.2 submission to OMB) and your graph that shows only US Passenger-Kilometers by Air in Millions have not been fixed.  In addition, the 2016 and 2017 data that we submitted to OMB in May is still not being shown on the graph.  Is there any timeline for getting these issues fixed?

Steven Beningo
U.S. Department of Transportation
Bureau of Transportation Statistics
1200 New Jersey Avenue SE, Room E34-301, RTS-34
Washington, DC 20590
(202) 366-9683



From: Beningo, Steven (OST)
Sent: Wednesday, May 15, 2019 5:12 PM
To: GSA/sdg-data-usa <reply@reply.github.com>
Subject: RE: [GSA/sdg-data-usa] Update indicator_9-1-2.csv (#30)

Kali,
      I have attached the source data in a spreadsheet form.  I am not seeing any weird 2015 data in the spreadsheet.
              Steve

**Pull request merged**
